### PR TITLE
Skipped install when config.php already exists

### PR DESCRIPTION
**Pull request by mawrkus**

### CODE REVIEW

**Comment by Froelund** [comment]
Thanks for contrib!
Wouldn't it be better to look for both configuration.php and config.php? As I understand, they both will be generated.

**Comment by mawrkus** [comment]
Yes, makes perfect sense :)

**Comment by mawrkus** [comment]
Just updated the PR.

**Comment by mawrkus** [comment]
Let me know if it's fine now and if we can close this PR and follow the next steps.

**Comment by Froelund** [comment]
I think it's fine, but I can't merge it :) Maybe @WellingGuzman can help

**Comment by WellingGuzman** [comment]
Thanks @mawrkus for the PR.

Also Thank you too @Froelund! :)

**Pull request merged**
